############################
# @author Elias De Hondt   #
# @see https://eliasdh.com #
# @since 24/11/2024        #
############################
---
apiVersion: v1
kind: Secret
metadata:
  name: sshserver-secret
  namespace: sshserver
type: Opaque
data:
  user: dXNlcg== # user
  password: Uk9PVDEyMzQ1Njc4OQ== # ROOT123456789
---